version: '3.8'

services:

  postgres:
    restart: always
    image: postgres:latest
    container_name: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=callback
    volumes:
      - ./repository/data:/var/lib/postgresql/data


  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always


  kafka:
    image: confluentinc/cp-kafka
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      LISTENERS: PLAINTEXT://kafka:9092
    restart: always


  clickhouse:
    image: yandex/clickhouse-server
    hostname: clickhouse
    container_name: clickhouse
    ports:
      - "9000:9000"
    volumes:
      - ./clickhouse/data:/var/lib/postgresql/data
    restart: always

  redis:
    image: bitnami/redis
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - /redis/data:/var/lib/redis/data
    restart: always
    environment:
       ALLOW_EMPTY_PASSWORD: "yes"

  grpc:
    container_name: grpc
    hostname: grpcserver
    depends_on:
      - postgres
      - kafka
      - clickhouse
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      PG_MIGRATIONS_PATH: "file://../../src/app/cmd/migrations"
    restart: always


#networks:
#  ch_ntw:
#    driver: bridge